spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format.sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
  profiles:
    active: dev

api:
  prefix: /api/v1