spring:
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5433/school-db
    username: school_admin
# demonstration purpose ||| don't do that
    password: password:)
    driver-class-name: org.postgresql.Driver

# email sender configuration
  mail:
    host: smtp.gmail.com
    username: EMAIL_ADDRESS
    password: EMAIL_PASSWORD
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# public and private-key ||| these aren't used anywhere - demonstration purpose ||| don't do that
rsa:
  private-key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURJVUZPVjhJRkxhQnplDQpDZkpEMDlSZGVjNzF3VFl2L3JGMTE4KzErVGpPWGFHNWp1dGwzNEs4UmZzaHZSMkQvbXlpbE1DOFRoNnIxeUcvDQpIVEFtQXVzYWU1RTlZaGxKenlybHA4MFN1R1hSbjFvM0t1RTlyei9pUmNMMFg4elVMVXFwbzRYYUVxU2hZd0VMDQpFaDNjU0M4R3lhMWtqUW43WjFuVWtlcFgvUFhUdXo2clJXTVFya3g1WUVUcEZtM0U4bStlY2JETW93Q0JTMnRqDQpORS9BSUdnRnpGM3dvSDZuL3FMZERxSHBkNnpLNG42dVBiT3k5c3lNNXVONVFGTHRRL0wyZ1lNQzRGQUJ6Q0QwDQpqbFNOWlpEamtkaE1SZ2V4aWthbElLNFMxNld2NFU5TkZ0V2dmT2Nmak1BSFhqRk1KUjk1VmRCR25DNStBNFJzDQo3VVY2TncxUEFnTUJBQUVDZ2dFQkFMWE51ZDgzTnBJUy8waEM3TC9FelZTOWppb2NYeXIyVldnb0pCdjhBeVBCDQpkVnZ0ckJaODRySXdMYnEwWXNwK3EyaHY2L0c4VVRnVGZFeHhtRmFYaFh3MnRGNXEzNXJPelJjODBmSndxL0N5DQpXWFlDbEFXaFBqRUdzZWVMMzJLZmJNbEVZZUxIMHVXcTdySjJrZVZ4R2tWbDI5cUw2NGhpaC9SWExzTUhFckpEDQovYVlqN2cwNVl1YXZJaENJY3F5N3pTOVFsTTdBSTkxN2hML1BRS3dPTElVdXlpTVFHazVVZS9KZzhDK0dyaUxNDQpSemJDNFBJRDc4SmxDK2kvdTY4SVVJWFRIcUFlYjMrcTlEMmUya3JsRExUQWQ1dXRtU2ovWVpsemV5YUdsNG83DQpUZ1A5djdYODVXSlFlQWFiVS9reGUvaU1FV01RS2FrSmtIRW9JK24rR1BrQ2dZRUErV2Y3OGt2TVJYeCt0UDZJDQo0UGRNTVhHQ3ZEZzNOUFN3SjZRV3pCMnVQTDlCK0FhSFFYVzNZd3huakJMYnRaZmhZbW9yWW9zYkF6NlBsR3ZtDQptelNNY2U4RWIxb0Q0dkg3YUs1TXVDaVRTTE04WjBJZGxKUXp1MUpJR2oreEd1eFIvcVVVYWlCODhrTzc1UjYzDQprZEtITmlkQjBidmp2dDlaQ2RzQTAwRTB1bTBDZ1lFQXpad1QreUprU3ZJdWRPYndrOU9WR0xTUEMvN3ZJVkNKDQpEdU9WQ2pkT011d0trUlZKZ293cGFkb09vNDh0bGNkTUxjeS8vVE0zankwYVY4S0M5Y1I3MGN1cFkwU0trVXpWDQpnSGpTaGdCeTVHVXVOL2NRcGxxdDNRZU1pK29LTHZNZFBsbTlaVFJjVGJZd0FSRWFCbTBpTWZxVmhCbU1FcGxODQpaRjhwTlZGVWtTc0NnWUVBaEh6R2kvblQ4MzJrMllUMU5YeHBEMExiVGgwV3hwek5EdUhOOG5RNTRLOUEzZjZwDQp6dzQzY3ZoZDhUejdWY1h1eHBiYm9TZUFIQU1aeHFCakNrT3A3OFFtdVBnNlpFNWpYVUpxSXRIN0czMkxNdGNlDQpXNVUydmVXQnc5L2R0dzJlcVFVTWlTdms4OVVqZFIwU0t2YUpPUzAxZTdLeDB1MVdvVE9qaHBWMjZ5a0NnWUFGDQpMNXVkYVBlb29FVWxzN0Y3dVFsNHJ3MHdtMFNDelpvM1l1d2VidGl0RmlFS0djUlo0NWtqejFreExPcFViY3R4DQpHRW43WS9CUnp5eHI3RDhMWGVKVm4xSnRhNHduTUEzdWlKMmV2YUlvT3BrWTFrVjRQSzlIOU9uSm1hU2FISTJ2DQpSZW91QkUwVHRMV3ZRVFFyMTFMV2VlQ05qV3RvQ0svWUNVSnIwdHBVTXdLQmdBTjZlUXBlMmluRk9BQ0ZrRWcwDQozc1NxOVIzUXUzbXNPUWJXR1UvRFo1djJqQmwrNWw5N29KZ1BTekVQdkd2Y0VDMWJWbG1ReUtsRTdRVDA4d0lpDQpXRENGV3JxWjF2OWpjN3p6UGsyWkFseEZFS0wrSE14SDh1cnJNTlpQbmJmSmtacFN1VlpQU2x6UE11TjhieER0DQpJaHR1am53SkhuL25MWERybkZ1aEs5bXoNCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0NCg==
  public-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeUZCVGxmQ0JTMmdjM2dueVE5UFUNClhYbk85Y0UyTC82eGRkZlB0Zms0emwyaHVZN3JaZCtDdkVYN0liMGRnLzVzb3BUQXZFNGVxOWNodngwd0pnTHINCkdudVJQV0laU2M4cTVhZk5FcmhsMFo5YU55cmhQYTgvNGtYQzlGL00xQzFLcWFPRjJoS2tvV01CQ3hJZDNFZ3YNCkJzbXRaSTBKKzJkWjFKSHFWL3oxMDdzK3EwVmpFSzVNZVdCRTZSWnR4UEp2bm5Hd3pLTUFnVXRyWXpSUHdDQm8NCkJjeGQ4S0IrcC82aTNRNmg2WGVzeXVKK3JqMnpzdmJNak9iamVVQlM3VVB5OW9HREF1QlFBY3dnOUk1VWpXV1ENCjQ1SFlURVlIc1lwR3BTQ3VFdGVscitGUFRSYlZvSHpuSDR6QUIxNHhUQ1VmZVZYUVJwd3VmZ09FYk8xRmVqY04NClR3SURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0NCg==

application:
  url: http://localhost:8080/api/v1

# defines whether to use real email sender or a fake one. Options: real / fake.
use-email-sender: fake